### PR TITLE
[MRG] Removed the unreachable bluetooth devices.

### LINKED ISSUE #275: Bluetooth scanning results should not contain unreachable devices
#### Problem description
In the bluetooth devices page, we have all the paired devices shown, but some of them are unreachable so we need to remove them. 

#### Steps to reproduce the problem
Open the skunkworks-crow, click `receive` using bluetooth, we can see some scanned devices and some of them are just bonded but unreachable. 

#### Expected behavior
We should show all available devices.

#### Other information 
@opendatakit-bot claim

### PR DESCRIPTION
**Pull request by huangyz0918**
Closes #275 

#### What has been done to verify that this works as intended?
I just removed the `addBondedDevices()` method, since we don't need all the paired devices. 
Those changes tested well in my Nexus 6P and Samsung Galaxy note3. 

#### Why is this the best possible solution? Were any other approaches considered?
Though we removed the `addBondedDevices()` method, but we can still see the differences between the paired devices and the unpaired devices. So I think this is the best solution.  

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
N/A
#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkCode` and confirmed all checks still pass OR confirm CircleCI build passes
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/opendatakit/share/blob/master/share_app/src/main/assets/open_source_licenses.html).

### CODE REVIEW

**Comment by huangyz0918** [comment]
This quick fix is ready for a review @lakshyagupta21 .

File: skunkworks_crow/src/main/java/org/odk/share/views/ui/bluetooth/BluetoothListAdapter.java [hunk 1]
```diff
@@ -69,7 +70,7 @@ public void onBindViewHolder(@NonNull final ViewHolder viewHolder, int position)
         int deviceBondState = device.getBondState();
         viewHolder.deviceName.setText(deviceName == null ? viewHolder.itemView.getResources().getString(R.string.bluetooth_instance_name_default) : deviceName);
         viewHolder.deviceAddress.setText(String.format("%s (%s)", deviceAddress,
-                deviceBondState == 10 ? context.getString(R.string.bluetooth_unpaired) : context.getString(R.string.bluetooth_paired)));
```
Comment (lakshyagupta21) [inline skunkworks_crow/src/main/java/org/odk/share/views/ui/bluetooth/BluetoothListAdapter.java]: Just a question what was this hardcoded 10 value?

Comment (huangyz0918) [reply skunkworks_crow/src/main/java/org/odk/share/views/ui/bluetooth/BluetoothListAdapter.java]: The same as `BOND_NONE`.

File: skunkworks_crow/src/main/java/org/odk/share/views/ui/bluetooth/BluetoothListAdapter.java [hunk 2]
```diff
@@ -69,7 +70,7 @@ public void onBindViewHolder(@NonNull final ViewHolder viewHolder, int position)
...
+                deviceBondState == BOND_NONE ? context.getString(R.string.bluetooth_unpaired) : context.getString(R.string.bluetooth_paired)));
         if (device.getBondState() == BOND_BONDED) {
```
Comment (lakshyagupta21) [inline skunkworks_crow/src/main/java/org/odk/share/views/ui/bluetooth/BluetoothListAdapter.java]: use `deviceBondState` in place of `device.getBondState()`
