### PR TITLE
[MRG] Fixed the storage permission handling progress.

### LINKED ISSUE #295: App not starting if permission is denied
#### Software and hardware versions 
Android vx.x.x, device used...

#### Problem description
App doesn't start if application doesn't have storage permission.

#### Steps to reproduce the problem

1. Reset the app if already installed.
2. Install the app.
3. Deny the storage permission.
4. Open app again.
5. Mark the checkbox selected.
6. Again deny the storage permission.
7. Try opening the app again, it won't start.
#### Expected behavior
App should ask user to enable the permissions(through dialog box) from the app settings.

### PR DESCRIPTION
**Pull request by huangyz0918**
Closes #295 

#### What has been done to verify that this works as intended?
I didn't use the permission dispatcher lib, since we already has the complete checking code, so I tried to fix this bug without a refactor. But I have tested with the permission dispatcher library as well, maybe something goes wrong with the injector, so the `OnPermissionDenied` would be called every time before I do any operations with the permission request dialog. So I just fixed the issue in the base of current code and make tests in my Nexus 6P (Android 9), everything works well.

#### Why is this the best possible solution? Were any other approaches considered?
N/A

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
N/A

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkCode` and confirmed all checks still pass OR confirm CircleCI build passes
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/opendatakit/share/blob/master/share_app/src/main/assets/open_source_licenses.html).

### CODE REVIEW

File: skunkworks_crow/src/main/java/org/odk/share/views/ui/main/MainActivity.java [hunk 1]
```diff
@@ -245,20 +251,40 @@ private void addListItemDivider() {
...
         super.onRequestPermissionsResult(requestCode, permissions, grantResults);
-
         switch (requestCode) {
             case STORAGE_PERMISSION_REQUEST_CODE:
                 if (grantResults[0] == PackageManager.PERMISSION_GRANTED) {
                     setUpLoader();
                 } else {
-                    //close the app if the permission is denied
-                    finish();
+                    if ((Build.VERSION.SDK_INT >= Build.VERSION_CODES.M &&
```
Comment (lakshyagupta21) [inline skunkworks_crow/src/main/java/org/odk/share/views/ui/main/MainActivity.java]: I think if this block is executed that means permission is already denied, why're we checking again for the permission?

Comment (huangyz0918) [reply skunkworks_crow/src/main/java/org/odk/share/views/ui/main/MainActivity.java]: Fixed

**Comment by huangyz0918** [comment]
This PR can be review first. @lakshyagupta21 Thanks.

File: skunkworks_crow/src/main/java/org/odk/share/views/ui/main/MainActivity.java [hunk 2]
```diff
@@ -245,20 +251,39 @@ private void addListItemDivider() {
...
```
Comment (lakshyagupta21) [inline skunkworks_crow/src/main/java/org/odk/share/views/ui/main/MainActivity.java]: Even this version check is redundant because every time the version is going to be greater than `M`, because you request only for the greater versions than `M`

Comment (huangyz0918) [reply skunkworks_crow/src/main/java/org/odk/share/views/ui/main/MainActivity.java]: But method `shouldShowRequestPermissionRationale` has a compiler check for API > 23, if we remove the API check, the code cannot pass the compiler.

File: skunkworks_crow/src/main/java/org/odk/share/views/ui/main/MainActivity.java [hunk 3]
```diff
@@ -245,20 +251,39 @@ private void addListItemDivider() {
     @Override
     public void onRequestPermissionsResult(int requestCode, @NonNull String[] permissions, @NonNull int[] grantResults) {
         super.onRequestPermissionsResult(requestCode, permissions, grantResults);
-
         switch (requestCode) {
```
Comment (lakshyagupta21) [inline skunkworks_crow/src/main/java/org/odk/share/views/ui/main/MainActivity.java]: And this switch case can be replaced with `if`, because switch is used when 3 or more items are present in the checklist.

Comment (huangyz0918) [reply skunkworks_crow/src/main/java/org/odk/share/views/ui/main/MainActivity.java]: Sure, will improve soon.

File: skunkworks_crow/src/main/java/org/odk/share/views/ui/main/MainActivity.java (hunk 2 above)
Comment (lakshyagupta21) [reply skunkworks_crow/src/main/java/org/odk/share/views/ui/main/MainActivity.java]: Oops, I forgot that ok for now lets keep it.
