### PR TITLE
worked on issue  #233

### LINKED ISSUE #233: When Writing Hotspot Password, OK Button Should Be Disabled Until 8 Chars
#### Software and hardware versions 
Galaxy Nexu API 24

#### Problem description
When Writing Hotspot Password, OK Button Should Be Disabled Until 8 input chars by the user.
Currently, the user is allowed to click the "OK" button even when chars<8 and a toast message appears afterwards showing the error. This toast message can also be removed with these changes.
#### Steps to reproduce the problem
1- Go to settings
2- Click Hotspot Password
3- Write characters less than 8.
4- Click OK
#### Expected behavior
OK button should be disabled until 8 input chars and enabled once the user has inputted 8 chars.

This issue can be solved using a TextWatcher.

#### Other information 
Things you tried, stack traces, related issues, suggestions on how to fix it...

### PR DESCRIPTION
**Pull request by devanshi7799**
Closes #233 

#### What has been done to verify that this works as intended?
I have run the application on my phone and it worked perfectly fine.

#### Why is this the best possible solution? Were any other approaches considered?
Here, i have used a Textwatcher.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkCode` and confirmed all checks still pass OR confirm CircleCI build passes
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/opendatakit/share/blob/master/share_app/src/main/assets/open_source_licenses.html).

### CODE REVIEW

**Comment by devanshi7799** [comment]
@lakshyagupta21 I have made this new pull request as the checks were continuously failing in the last one. 
@manit-alokbatham thank you so much for your help. :)

**Comment by manit-alokbatham** [comment]
> @lakshyagupta21 I have made this new pull request as the checks were continuously failing in the last one.
> @manit-alokbatham thank you so much for your help. :)

Welcome @devanshi7799

File: skunkworks_crow/src/main/java/org/odk/share/views/ui/settings/SettingsActivity.java [hunk 1]
```diff
@@ -177,25 +183,70 @@ private ViewGroup getRootView() {
...
     private void showPasswordDialog() {
-        AlertDialog.Builder builder = new AlertDialog.Builder(this);
         LayoutInflater factory = LayoutInflater.from(this);
 
         View dialogView = factory.inflate(R.layout.dialog_password_til, null);
+
         TextInputLayout tlPassword = dialogView.findViewById(R.id.et_password_layout);
         tlPassword.getEditText().setText(prefs.getString(PreferenceKeys.KEY_HOTSPOT_PASSWORD, getString(R.string.default_hotspot_password)));
 
+        edtpass = (TextInputEditText) dialogView.findViewById(R.id.edtpass);
```
Comment (Chromicle) [inline skunkworks_crow/src/main/java/org/odk/share/views/ui/settings/SettingsActivity.java]: @devanshi7799 great work 🎉, but why are you making new callback of view `edtpass` till now we are  used `tlpassword.getEditText()` do not create two callbacks people may confuse between two make it one,

If you are thinking to use callback using `id`, do not use `findViewById` we are using one library called [Butter Knife](https://github.com/JakeWharton/butterknife) for callback of views can you please use that

File: skunkworks_crow/src/main/java/org/odk/share/views/ui/settings/SettingsActivity.java [hunk 2]
```diff
@@ -177,25 +183,70 @@ private ViewGroup getRootView() {
...
+
+        alertDialog.setOnShowListener(new DialogInterface.OnShowListener() {
+
+            @Override
+            public void onShow(DialogInterface dialog) {
+
+                edtpass.addTextChangedListener(new TextWatcher() {
+                    @Override
+                    public void beforeTextChanged(CharSequence s, int start, int count, int after) {
+                        ((AlertDialog) dialog).getButton(AlertDialog.BUTTON_POSITIVE).setEnabled(false);
```
Comment (lakshyagupta21) [inline skunkworks_crow/src/main/java/org/odk/share/views/ui/settings/SettingsActivity.java]: no need to do this, by default set it disabled.

File: skunkworks_crow/src/main/java/org/odk/share/views/ui/settings/SettingsActivity.java [hunk 3]
```diff
@@ -177,25 +183,70 @@ private ViewGroup getRootView() {
...
+                    }
+
+                    @Override
+                    public void onTextChanged(CharSequence s, int start, int before, int count) {
+
+                        if (edtpass.getText().toString().length() >= 8) {
```
Comment (lakshyagupta21) [inline skunkworks_crow/src/main/java/org/odk/share/views/ui/settings/SettingsActivity.java]: Instead of having two `if` statement, modify it to `if else` statement.

Comment (lakshyagupta21) [inline skunkworks_crow/src/main/java/org/odk/share/views/ui/settings/SettingsActivity.java]: Have you verified whether getText is giving `null` or not when you type the password and then again removes all characters from edit text. Just curious whether it gives empty string or null. :-/

**Comment by lakshyagupta21** [comment]
@devanshi7799 Thanks for raising a PR, just wanted to point out a few things which you can improve in the future,
1. PR title should give a brief description of the changes done in the code.
2. Make sure to complete the PR template, also mark the checkboxes if you've done that otherwise PRs can't be merged, this is the standard that we follow in each PR review. For now, it's fine because no major changes are done but for big PRs it's required.
3. And you can work on the same PR even if you've committed some mistakes in that or if you're having merge conflicts or any other issues, please let us know over here or on the slack channel we would be happy to help.

**Comment by devanshi7799** [comment]
@lakshyagupta21 @Chromicle I will take care about these things in future.

File: skunkworks_crow/src/main/java/org/odk/share/views/ui/settings/SettingsActivity.java [hunk 4]
```diff
@@ -177,25 +183,68 @@ private ViewGroup getRootView() {
...
+                    public void beforeTextChanged(CharSequence s, int start, int count, int after) {
+                 
+                    }
+
+                    @Override
+                    public void onTextChanged(CharSequence s, int start, int before, int count) {
+
+                        if (edtpass.getText().toString().length() >= 8) {
+                            ((AlertDialog) dialog) .getButton(AlertDialog.BUTTON_POSITIVE).setEnabled(true);
+                        } else if (edtpass.getText().toString().length() < 8) {
```
Comment (lakshyagupta21) [inline skunkworks_crow/src/main/java/org/odk/share/views/ui/settings/SettingsActivity.java]: `else if` condition is not required either the number of chars is >= 8 or < 8 so we can do it in just `if and else` condition.

**Comment by Chromicle** [comment]
@lakshyagupta21 I tested this branch and it is working perfectly you can merge this

**Comment by lakshyagupta21** [comment]
Thanks @devanshi7799  , for picking up the issue and solving it, its nice to see you getting familiar with the code and the app flow. Hope to see more PRs and good github issues from your side.
