### PR TITLE
fix: MainActivity UI is updating after updating in database

### LINKED ISSUE #309: After form transfer status on Main screen is not updated correctly
#### Software and hardware versions 
Android vx.x.x, device used...

#### Problem description
Whenever any instance form transfer happens, there is some discrepancy in reviewed and unreviewed status on the main screen.
#### Steps to reproduce the problem
1. Download all the available forms(at least two is needed to distinguish the status) from the default server on both sender and receiver.
2. Create one instance of Collect-Location form in one device and send it to the other.
3. Go on home screen and check the status of unreviewed form, it shows the unreviewed counter of `All widgets` form.
#### Expected behavior
It should show the unreviewed status for Collect-location form.
#### Other information 
There is some code problem in FormsAdapter class where we're querying the instances and transfer table.
Things you tried, stack traces, related issues, suggestions on how to fix it...

### PR DESCRIPTION
**Pull request by Chromicle**
Closes #309 

#### What has been done to verify that this works as intended?
- Checked whether `reviewed` and `unreviewed` count is getting perfectly or not 
- Checked whether the count is updating when on pressing the back button 
- Checked whether any new warnings are produced by adding this code
- Checked any tests are failing
- Checked by changing the orientation of the device

#### Why is this the best possible solution? Were any other approaches considered?
Removed previous approach of the query(checking every time status of form) and added the query for getting `receivedCount` and `reviewedCount` so, we can get the unReviewed count with `receivedCount-reviewedCount` and Updated the forms adapter when user presses back button from another activity in `onResume`

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

By updating the UI in `onResume` so, the user no need to restart the activity and get the change 

#### GIF
ezgif com-video-to-gif (3)

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkCode` and confirmed all checks still pass OR confirm CircleCI build passes
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/opendatakit/share/blob/master/share_app/src/main/assets/open_source_licenses.html).

### CODE REVIEW

**Comment by huangyz0918** [comment]
Thanks @Chromicle , this is an important fix. The code looks good to me but I need sometime to test and make sure this fix is valid and safe.

File: skunkworks_crow/src/main/java/org/odk/share/views/ui/main/MainActivity.java [hunk 1]
```diff
@@ -107,6 +107,15 @@ protected void onCreate(Bundle savedInstanceState) {
         addListItemDivider();
     }
 
+    @Override
+    public void onResume() {
+        super.onResume();
+        //update the list
```
Comment (huangyz0918) [inline skunkworks_crow/src/main/java/org/odk/share/views/ui/main/MainActivity.java]: The code is very clear and we don't need this comment.

Comment (Chromicle) [reply skunkworks_crow/src/main/java/org/odk/share/views/ui/main/MainActivity.java]: Yeah, I updated.
can you please have a look at my previous [PR's](https://github.com/opendatakit/skunkworks-crow/pulls/Chromicle)

**Comment by huangyz0918** [comment]
@Chromicle Thanks a lot! I'm always looking for the day that this issue can be addressed, it's you!
