### PR TITLE
[MRG] dialogs to the bluetooth sender/receiver

### LINKED ISSUE #268: Bluetooth is still 'ON' even if the connection is complete/canceled.
according to the [comment](https://github.com/opendatakit/skunkworks-crow/pull/260#issuecomment-512504145)

#### Steps to reproduce the problem
Using bluetooth feature to transfer forms, cancel the progress or waiting for the progress completed. The bluetooth still on.

#### Expected behavior
Bluetooth should be disabled.

#### Other information 
@opendatakit-bot claim

### LINKED ISSUE #269: Show dialog to get the confirmation for stopping the bluetooth connection.
#### Problem description
according to this [comment](https://github.com/opendatakit/skunkworks-crow/pull/260#issuecomment-512504145), we should add a confirm dialog to ask our user for stopping connections.

#### Steps to reproduce the problem
Press the `back` button. 

#### Expected behavior
When we press the `back` button, or want to quit the transferring page. We should pop up a dialog asking the confirmation for stopping the bluetooth connection. 

#### Other information 
@opendatakit-bot claim

### LINKED ISSUE #297: Crash happen when waiting for receiver to connect
#### Software and hardware versions 
Android v7.1 Xiaomi Redmi 4

#### Problem description
While waiting for the receiver to connect to sender's BlueTooth, after some duration I see my app crashed. Was able to reproduce while testing #270 

#### Steps to reproduce the problem
1. Send forms using BlueTooth
2. Wait for receiver to connect.
3. Press back and wait for 120sec to see your app restart.

#### Expected behavior
App should not crash
#### Other information
Stack Trace
```
019-08-11 14:44:37.697 2753-2753/org.odk.share E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.odk.share, PID: 2753
    android.view.WindowManager$BadTokenException: Unable to add window -- token android.os.BinderProxy@59b7603 is not valid; is your activity running?
        at android.view.ViewRootImpl.setView(ViewRootImpl.java:702)
        at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:344)
        at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:94)
        at android.app.Dialog.show(Dialog.java:329)
        at org.odk.share.views.ui.bluetooth.BtSenderActivity$1.onFinish(BtSenderActivity.java:248)
        at android.os.CountDownTimer$1.handleMessage(CountDownTimer.java:127)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:163)
        at android.app.ActivityThread.main(ActivityThread.java:6238)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:933)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)
```

### PR DESCRIPTION
**Pull request by huangyz0918**
Closes #268 
Closes #269 
Closes #297 

#### What has been done to verify that this works as intended?
built an alert dialog for asking if we should disable the bluetooth. And I have tested in my Nexus 6P (Android 8.0.1) and Samsung Galaxy Note3 (Android 5.0), everything goes well.

attached please find screenshots when press `back` button on the devices.

|||
|:--:|:--:|
|[](https://i.loli.net/2019/07/18/5d2fecea395bc15491.png)|[](https://i.loli.net/2019/07/18/5d2fecea4dad177662.png)|

#### Why is this the best possible solution? Were any other approaches considered?
I added two dialog when called `onBackPressed`, and this is a best way to handle that issue.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
N/A

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkCode` and confirmed all checks still pass OR confirm CircleCI build passes
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/opendatakit/share/blob/master/share_app/src/main/assets/open_source_licenses.html).

### CODE REVIEW

File: skunkworks_crow/src/main/java/org/odk/share/views/ui/bluetooth/BtReceiverActivity.java [hunk 1]
```diff
@@ -225,4 +234,22 @@ protected void onDestroy() {
         super.onDestroy();
         unregisterReceiver(bluetoothReceiver);
     }
+
+    @Override
+    public void onBackPressed() {
```
Comment (lakshyagupta21) [inline skunkworks_crow/src/main/java/org/odk/share/views/ui/bluetooth/BtReceiverActivity.java]: In receiver we should not ask like 'To disable bluetooth', rather we should ask `Do you want to stop the receiving` or any other meaningful message, this way we'll close the connection and clean up the half downloaded forms/files which were in progress to avoid any mismatch in next transaction.

Comment (huangyz0918) [reply skunkworks_crow/src/main/java/org/odk/share/views/ui/bluetooth/BtReceiverActivity.java]: Sure, will fix soon.

**Comment by huangyz0918** [comment]
Please do not merge this PR first @lakshyagupta21 , I found an issue inside these changes: We can only send successful once in this PR, next time when we trying to send/receive, it seems something was closed and the receiver will throw an exception,

```
07-18 12:10:02.189 26457-26881/org.odk.share E/DownloadJob: java.io.IOException: read failed, socket might closed or timeout, read ret: -1
        at android.bluetooth.BluetoothSocket.readAll(BluetoothSocket.java:637)
        at android.bluetooth.BluetoothSocket.readInt(BluetoothSocket.java:648)
        at android.bluetooth.BluetoothSocket.connect(BluetoothSocket.java:400)
        at org.odk.share.tasks.DownloadJob.setupDataStreamsAndReceive(DownloadJob.java:137)
        at org.odk.share.tasks.DownloadJob.initJob(DownloadJob.java:124)
        at org.odk.share.tasks.DownloadJob.onRunJob(DownloadJob.java:106)
        at com.evernote.android.job.Job.runJob(Job.java:132)
        at com.evernote.android.job.JobExecutor$JobCallable.runJob(JobExecutor.java:191)
        at com.evernote.android.job.JobExecutor$JobCallable.call(JobExecutor.java:176)
        at com.evernote.android.job.JobExecutor$JobCallable.call(JobExecutor.java:159)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:818)
```

Any ideas?

File: skunkworks_crow/src/main/java/org/odk/share/views/ui/bluetooth/BtSenderActivity.java [hunk 2]
```diff
@@ -145,4 +147,24 @@ protected void onPause() {
...
         compositeDisposable.clear();
     }
+
+    @Override
+    public void onBackPressed() {
+        if (BluetoothUtils.isBluetoothEnabled()) {
+            new AlertDialog.Builder(this)
+                    .setTitle(getString(R.string.stop_sending))
+                    .setPositiveButton(R.string.stop, (DialogInterface dialog, int which) -> {
+                        senderService.cancel();
```
Comment (huangyz0918) [inline skunkworks_crow/src/main/java/org/odk/share/views/ui/bluetooth/BtSenderActivity.java]: I think this issue may comes from here

**Comment by huangyz0918** [comment]
I think this PR is ready @lakshyagupta21 , I have tested and without any regressions.

File: skunkworks_crow/src/main/java/org/odk/share/views/ui/bluetooth/BtReceiverActivity.java [hunk 3]
```diff
@@ -311,4 +320,24 @@ protected void onDestroy() {
...
+        if (BluetoothUtils.isBluetoothEnabled()) {
```
Comment (lakshyagupta21) [inline skunkworks_crow/src/main/java/org/odk/share/views/ui/bluetooth/BtReceiverActivity.java]: What if bluetooth is disabled by user from the `Device notification drawer`, user won't be able to navigate back.

File: skunkworks_crow/src/main/res/values/strings.xml [hunk 4]
```diff
@@ -51,6 +51,9 @@
     <string name="ok">OK</string>
     <string name="canceled">Canceled</string>
     <string name="stop_sending">Stop Sending</string>
+    <string name="stop_sending_msg">Do you want to stop sending?</string>
+    <string name="disable_bluetooth">Disable bluetooth?</string>
```
Comment (lakshyagupta21) [inline skunkworks_crow/src/main/res/values/strings.xml]: Remove `?`

File: skunkworks_crow/src/main/res/values/strings.xml [hunk 5]
```diff
@@ -51,6 +51,9 @@
...
+    <string name="disable_bluetooth_msg">Do you want to quit and disable the bluetooth?</string>
```
Comment (lakshyagupta21) [inline skunkworks_crow/src/main/res/values/strings.xml]: change it to `Do you want to disable the bluetooth and stop receiving of forms?`

File: skunkworks_crow/src/main/java/org/odk/share/views/ui/bluetooth/BtReceiverActivity.java [hunk 6]
```diff
@@ -311,4 +320,24 @@ protected void onDestroy() {
...
+            new AlertDialog.Builder(this)
+                    .setTitle(getString(R.string.disable_bluetooth))
+                    .setMessage(getString(R.string.disable_bluetooth_msg))
+                    .setPositiveButton(android.R.string.yes, (DialogInterface dialog, int which) -> {
+                        receiverService.cancel();
+                        BluetoothUtils.disableBluetooth();
+                        super.onBackPressed();
+                    })
+                    .setNegativeButton(android.R.string.no, (DialogInterface dialog, int which) -> {
+                        receiverService.cancel();
```
Comment (lakshyagupta21) [inline skunkworks_crow/src/main/java/org/odk/share/views/ui/bluetooth/BtReceiverActivity.java]: If the user presses `Cancel` button then why're we canceling the receiver service and navigating back the user to the main screen. Ideally, only dialog box should be dismissed.

File: skunkworks_crow/src/main/java/org/odk/share/views/ui/bluetooth/BtReceiverActivity.java [hunk 7]
```diff
@@ -93,6 +95,13 @@ protected void onCreate(Bundle savedInstanceState) {
         setTitle(getString(R.string.connect_bluetooth_title));
         setSupportActionBar(toolbar);
 
+        progressDialog = new ProgressDialog(this);
```
Comment (lakshyagupta21) [inline skunkworks_crow/src/main/java/org/odk/share/views/ui/bluetooth/BtReceiverActivity.java]: Why creating a object in `onCreate`? It should be created whenever and wherever you want to show the dialog.

Comment (huangyz0918) [reply skunkworks_crow/src/main/java/org/odk/share/views/ui/bluetooth/BtReceiverActivity.java]: resolved

File: skunkworks_crow/src/main/java/org/odk/share/views/ui/bluetooth/BtReceiverActivity.java (hunk 3 above)
Comment (huangyz0918) [reply skunkworks_crow/src/main/java/org/odk/share/views/ui/bluetooth/BtReceiverActivity.java]: fixed

File: skunkworks_crow/src/main/java/org/odk/share/views/ui/bluetooth/BtSenderActivity.java [hunk 8]
```diff
@@ -239,14 +246,17 @@ public void onTick(long millisUntilFinished) {
...
+                    alertDialog.show();
+                }
             }
         }.start();
     }
 
     @Override
     protected void onResume() {
         super.onResume();
+        senderService.startUploading(formIds, mode);
```
Comment (lakshyagupta21) [inline skunkworks_crow/src/main/java/org/odk/share/views/ui/bluetooth/BtSenderActivity.java]: This will be called whenever user goes to device home screen and opens the app. So do you think this is the right place to call this?

Comment (huangyz0918) [reply skunkworks_crow/src/main/java/org/odk/share/views/ui/bluetooth/BtSenderActivity.java]: Sorry, I will fix this soon 😢

**Comment by huangyz0918** [comment]
This PR is ready for review @lakshyagupta21 , improvements for dialogs, can be review along with #281 , thanks.

File: skunkworks_crow/src/main/java/org/odk/share/views/ui/bluetooth/BtReceiverActivity.java [hunk 9]
```diff
@@ -96,6 +98,7 @@ protected void onCreate(Bundle savedInstanceState) {
         // checking for if bluetooth enabled
         if (!BluetoothUtils.isBluetoothEnabled()) {
             BluetoothUtils.enableBluetooth();
+            Toast.makeText(this, getString(R.string.turning_on_bluetooth_message), Toast.LENGTH_SHORT).show();
             BtReceiverActivityPermissionsDispatcher.updateDeviceListWithPermissionCheck(this);
```
Comment (lakshyagupta21) [inline skunkworks_crow/src/main/java/org/odk/share/views/ui/bluetooth/BtReceiverActivity.java]: Ideally Bluetooth should not be triggered if location permission is not there.

Comment (huangyz0918) [reply skunkworks_crow/src/main/java/org/odk/share/views/ui/bluetooth/BtReceiverActivity.java]: Thanks a lot for checking this! I found some more places that I can improve, you can refer to the updates.

Comment (huangyz0918) [reply skunkworks_crow/src/main/java/org/odk/share/views/ui/bluetooth/BtReceiverActivity.java]: We have already call update devices list method in `initEvents()` method, so we don't have to call that again in `onCreate()`, and I moved the enable bluetooth method into the method required location permission, now it may looks fine.

**Comment by lakshyagupta21** [comment]
> Closes #294

Were you able to reproduce the issue? It looks like you addressed the fix for that bug.

**Comment by huangyz0918** [comment]
> Were you able to reproduce the issue? It looks like you addressed the fix for that bug.

Oh, sorry, that is a mistake, it is #297  . #294 is still active @lakshyagupta21 .

**Comment by lakshyagupta21** [comment]
When transfer is done at the receiver's end, it still shows the list of Bluetooth devices screen and when I press back it says that 'Do you want to disable the bluetooth and stop sending/receiving of forms?' and at the sender's end when transfer is completed status is shown on the screen and when I press back it should disable the bluetooth when the transfer is completed.

**Comment by huangyz0918** [comment]
@lakshyagupta21 I improve the PR with what you suggested, and fix the `socket closed or timeout` error, please review, thanks!
