### PR TITLE
[#223] adds checks onBackPress()

### LINKED ISSUE #223: Stop dialog is still shown if hotspot is not enabled.
#### Software and hardware versions 
Android v7.1

#### Problem description
If user doesn't trigger hotspot from the settings screen, then it still asks  `stop sending` when the user taps back button.

#### Steps to reproduce the problem
1. Tap on 'Send' button.
2. Select forms to send.
3. Tap on 'Send'
4. Tap on 'Settings'
5. Don't enable from the settings screen opened (press back button)
5. A screen shows message 'Problem in creating hotspot'
6. Press the back button
7. Dialog is shown to notify a user to stop sending the forms
#### Expected behaviour
No dialog should be shown to the user if hotspot not started.
#### Other information 
Things you tried, stack traces, related issues, suggestions on how to fix it...

### PR DESCRIPTION
**Pull request by nishontan**
Closes #223 

#### What has been done to verify that this works as intended?

   1.  Tap on 'Send' button.
   2.  Select forms to send.
   3.  Tap on 'Send'
   4.  Tap on 'Settings'
   5.   Don't enable from the settings screen opened (press back button)
   6.   A screen shows message 'Problem in creating hotspot'
   7.   Press the back button
   8.  Dialog is not shown to notify a user to stop sending the forms

#### Why is this the best possible solution? Were any other approaches considered?
It satisfies the stated expected behaviour in the issue. Maybe wrap the codeblock
```
stopHotspot();
finish();
````
in a method named `exitSafely()`
  

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
- User pressed back button,``stopHotspotAlertDialog()`` is only show if hotspot is actually active i.e. ``isHotspotRunning`` is set to true 

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkCode` and confirmed all checks still pass OR confirm CircleCI build passes
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/opendatakit/share/blob/master/share_app/src/main/assets/open_source_licenses.html).

### CODE REVIEW

**Comment by nishontan** [comment]
Why did the checks fail 🤔

**Comment by shobhitagarwal1612** [comment]
Try rerunning the circle CI task. It seems to be the problem with CircleCI

**Comment by shobhitagarwal1612** [comment]
Please fix merge conflicts

File: skunkworks_crow/src/main/java/org/odk/share/activities/SendActivity.java [hunk 1]
```diff
@@ -130,6 +130,12 @@ protected void onCreate(Bundle savedInstanceState) {
 
     @Override
     public void onBackPressed() {
+        if (!isHotspotRunning) {
+            stopHotspot();
```
Comment (shobhitagarwal1612) [inline skunkworks_crow/src/main/java/org/odk/share/activities/SendActivity.java]: If the hotspot is not enabled then why are we calling `stopHotspot`?

File: skunkworks_crow/src/main/java/org/odk/share/activities/SendActivity.java [hunk 2]
```diff
@@ -130,6 +130,12 @@ protected void onCreate(Bundle savedInstanceState) {
...
+            finish();
+            return;
```
Comment (shobhitagarwal1612) [inline skunkworks_crow/src/main/java/org/odk/share/activities/SendActivity.java]: Instead of returning here, use if-else block

File: skunkworks_crow/src/main/java/org/odk/share/activities/SendActivity.java (hunk 1 above)
Comment (nishontan) [reply skunkworks_crow/src/main/java/org/odk/share/activities/SendActivity.java]: I blindly copy pasted positive button callback from `stopHotspotAlertDialog`
I agree and understand that block is unnecessary now.
