### PR TITLE
Solves crash issue, due to missing cursor check.

### LINKED ISSUE #111: App crashes on clicking the send button in FilledFormsFragment
#### Problem Description:
App crashes when we click on the send button after selecting some forms. 

#### Steps to reproduce:
1. Get a blank form(like All widgets) in collect.
2. Fill it and save it.
3. Now launch Share, and try to send the filled form.
4.  You will notice the crash there.

> java.lang.RuntimeException: Unable to destroy activity {org.odk.share/org.odk.share.activities.SendFormsActivity}: android.database.StaleDataException: Attempted to access a cursor after it has been closed.
        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4746)
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4764)
        at android.app.ActivityThread.-wrap5(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1854)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:187)
        at android.app.ActivityThread.main(ActivityThread.java:7025)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:514)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:888)

### PR DESCRIPTION
**Pull request by DreamyPhobic**
Closes #111

#### What has been done to verify that this works as intended?
Verified in physical device Realme U1, Android 8.1.

#### Why is this the best possible solution? Were any other approaches considered?
Unchecked direct access to cursor was causing StaleDataException. Adding cursor-close-check solves this.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew pmd checkstyle lint findbugs` and confirmed all checks still pass OR confirm CircleCI build passes
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/opendatakit/share/blob/master/share_app/src/main/assets/open_source_licenses.html).

### CODE REVIEW

File: share_app/src/main/java/org/odk/share/adapters/InstanceAdapter.java [hunk 1]
```diff
@@ -61,7 +61,10 @@ public void onClick(View v) {
 
     @Override
     public int getItemCount() {
-        return cursor.getCount();
+        if (!cursor.isClosed()) {
```
Comment (shobhitagarwal1612) [inline share_app/src/main/java/org/odk/share/adapters/InstanceAdapter.java]: This can be simplified using a ternary operator

**Comment by shobhitagarwal1612** [comment]
Merging this PR would mean that no filled form instances would show up even if instances are available when the cursor is closed. So, instead of falling back to prevent crash by not showing the instances,  we should try to understand why the cursor is getting closed in the first place

**Comment by DreamyPhobic** [comment]
I tried to reproduce it on other devices and emulator but didn't get any error like this. So I think adding this check won't affect any users.

**Comment by DreamyPhobic** [comment]
This error just coming up in my device.

**Comment by shobhitagarwal1612** [comment]
Please resolve the conflicts and this looks good to be merged

**Comment by shobhitagarwal1612** [comment]
This doesn't look correct. It says 45 commits!!!

**Comment by shobhitagarwal1612** [comment]
Are you merging to the remote `master` branch or your forked `master` branch?

**Comment by DreamyPhobic** [comment]
I have just pushed the new changes to my forked Github branch, I don't know why these already committed changes coming along.

**Comment by DreamyPhobic** [comment]
Please suggest something, how can I correct it?

**Comment by huangyz0918** [comment]
@DreamyPhobic It seems you have merged remote master into your forked branch. You have two way to go, the first is rebasing, the other is close this PR and open a new one (for security, you should make sure your forked master is even with upstream master, then checkout to a new branch).

**Comment by huangyz0918** [comment]
I recommend you to get familiar with git and git workflow before contributing. You can refer to [this](https://www.atlassian.com/git/tutorials/rewriting-history/git-rebase).

**Comment by shobhitagarwal1612** [comment]
@DreamyPhobic Were you able to figure out the git issue?

**Comment by DreamyPhobic** [comment]
Sorry for inconvenience, I will open a new PR.

**Comment by shobhitagarwal1612** [comment]
Have you tried out the solution as mentioned here https://github.com/opendatakit/skunkworks-crow/pull/172#issuecomment-471211596?

**Comment by DreamyPhobic** [comment]
I tried but now the branch has diverged, it's getting too much confusing for me.

**Comment by DreamyPhobic** [comment]
I think now it's fine. @shobhitagarwal1612, please review.
