### PR TITLE
fix: multiple dialogs for location access

### LINKED ISSUE #311: bug: multiple dialogs appearing for requesting location access
#### Software and hardware versions 
Android v9.x.x, Vivo Z1 Pro

#### Problem description
When sending forms, the dialog for turn on the location is opening multiple times.
odk

#### Steps to reproduce the problem
Go to send blank form tab. Select the forms to send and click on the send button. If the location is not turned on, multiple dialogs will appear.

#### Expected behavior
A single dialog should be shown only.

### PR DESCRIPTION
**Pull request by naman653**
Closes #311 

#### What has been done to verify that this works as intended?
Tested this on my Vivo Z1 Pro device running on Android v9.x.x

#### Why is this the best possible solution? Were any other approaches considered?
NA

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
It ensures better stability of app as multiple dialogs were using a lot of android resources which was slowing down the whole android framework.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkCode` and confirmed all checks still pass OR confirm CircleCI build passes
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/opendatakit/share/blob/master/share_app/src/main/assets/open_source_licenses.html).

### CODE REVIEW

**Comment by naman653** [comment]
@lakshyagupta21 Please review this.

File: skunkworks_crow/src/main/java/org/odk/share/views/ui/hotspot/HpSenderActivity.java [hunk 1]
```diff
@@ -448,10 +449,26 @@ private void checkLocationPermission() {
 
         if (Build.VERSION.SDK_INT < Build.VERSION_CODES.M ||
                 checkSelfPermission(Manifest.permission.ACCESS_FINE_LOCATION) == PackageManager.PERMISSION_GRANTED) {
-
             toggleHotspot();
         } else {
-            requestPermissions(new String[]{Manifest.permission.ACCESS_COARSE_LOCATION}, LOCATION_PERMISSION_REQUEST_CODE);
+            if (ActivityCompat.shouldShowRequestPermissionRationale(this,
+                    Manifest.permission.ACCESS_FINE_LOCATION)) {
```
Comment (huangyz0918) [inline skunkworks_crow/src/main/java/org/odk/share/views/ui/hotspot/HpSenderActivity.java]: Where is the original `ACCESS_COARSE_LOCATION`?

**Comment by naman653** [comment]
Thanks, @huangyz0918 for pointing out the issues. Please review now.

**Comment by huangyz0918** [comment]
Looks good to me, let's ask @lakshyagupta21 for his opinion.

File: skunkworks_crow/src/main/java/org/odk/share/views/ui/hotspot/HpSenderActivity.java [hunk 2]
```diff
@@ -447,11 +448,25 @@ private void createAlertDialog(String title, String message) {
     private void checkLocationPermission() {
 
         if (Build.VERSION.SDK_INT < Build.VERSION_CODES.M ||
-                checkSelfPermission(Manifest.permission.ACCESS_FINE_LOCATION) == PackageManager.PERMISSION_GRANTED) {
+                checkSelfPermission(Manifest.permission.ACCESS_COARSE_LOCATION) == PackageManager.PERMISSION_GRANTED) {
```
Comment (lakshyagupta21) [inline skunkworks_crow/src/main/java/org/odk/share/views/ui/hotspot/HpSenderActivity.java]: Why changing the fine location to coarse location, and have you tested transferring forms ater this change?

Comment (naman653) [reply skunkworks_crow/src/main/java/org/odk/share/views/ui/hotspot/HpSenderActivity.java]: I understand what you are saying, but why we are using ACCESS_FINE_LOCATION in condition check but using ACCESS_COARSE_LOCATION while requesting permission.

Comment (lakshyagupta21) [reply skunkworks_crow/src/main/java/org/odk/share/views/ui/hotspot/HpSenderActivity.java]: We're using Course Location at both the places, can you point me to the actual line where you have seen this issue?

Comment (naman653) [reply skunkworks_crow/src/main/java/org/odk/share/views/ui/hotspot/HpSenderActivity.java]: I am saying why are we using FINE_LOCATION in the review you mentioned above, but COARSE_LOCATION at other places.

Comment (lakshyagupta21) [reply skunkworks_crow/src/main/java/org/odk/share/views/ui/hotspot/HpSenderActivity.java]: There could be a miss while reviewing the code, as much as I remember when you ask for location permission it shows only one dialog and that allows both the permissions but if in our case if we need only one of the permission to execute the method or the piece of code that I think we should stick with the same permission not both of them. Thanks @naman653  for poinitng this out. It would be helpful if you can open a issue regarding this.

Comment (naman653) [reply skunkworks_crow/src/main/java/org/odk/share/views/ui/hotspot/HpSenderActivity.java]: Happy to do that. But for which permission we should go for?

Comment (lakshyagupta21) [reply skunkworks_crow/src/main/java/org/odk/share/views/ui/hotspot/HpSenderActivity.java]: That needs to be checked, if we're using both the permissions in our code then it's in our best interest to check for both of them while asking to the user.

Comment (naman653) [reply skunkworks_crow/src/main/java/org/odk/share/views/ui/hotspot/HpSenderActivity.java]: Sorry for late replying, as I was busy with my mid terms. I think we should go for Coarse Location as it was being used before, and was working just fine before.

Comment (naman653) [reply skunkworks_crow/src/main/java/org/odk/share/views/ui/hotspot/HpSenderActivity.java]: Also, tell me what should be done with this PR.

Comment (naman653) [reply skunkworks_crow/src/main/java/org/odk/share/views/ui/hotspot/HpSenderActivity.java]: @lakshyagupta21 Please review

**Comment by naman653** [comment]
@lakshyagupta21 Can you please review this or suggest someone who can. Seems like the community is not that active. It's been many days since I opened the PR. I want to work on more issues as there is so much that can be done on this application.

**Comment by lakshyagupta21** [comment]
Thanks @naman653 for raising the PR,  this project is at its initial step we're still making it mature enough so that the features of this app doesn't break in field easily. So getting attention of lot of contributors will also take time,  currently me and @shobhitagarwal1612 are the ones who are involved in the PR reviews so I think he might be busy sonewhere in his work otherwise he would've reviewed and I'm travelling this week so I wasn't able to review. And btw no one is stopping you to work on other issues and PRs,  feel free to work on other issues,  we'll take a look at it soon.

**Comment by lakshyagupta21** [comment]
@naman653 Sorry for late reply.
Code wise things looks good to me, I just wanted to check with you have you tried sending a form using hotspot method from one device to another? Its not working for me I'm trying to send from Android 7.1 to Android 9, it could be some other issue but just wanted to check if it's working for you or not.

**Comment by naman653** [comment]
Yes, I was also unable to send forms. But I think it's another issue, as I was unable to send forms prior to the changes. There are older issues which points to the same problem #191, #197.

**Comment by lakshyagupta21** [comment]
@naman653 , Thanks for taking a look into the issue and sorry for keeping this PR in review state for so long.
Merging this PR as the form issue is already there on the master, and I think we need to fix this asap otherwise it would create some problem while testing other issuees and PRs.
